name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: breuninger-core-gitbeaver
  LOCATION: europe-west1
  TF_VERSION: 1.1.8
  NETORK: projects/breuninger-core/locations/europe-west3/connectors/breuninger-core-network
  IMAGE_REGION: eu.gcr.io
  SERVICE_ACCOUNT: gitbeaver-run-sa
  RUN_GIT: https://github.com/kneissler
  RUN_REPO: provisioning-main
  RUN_TAG: main
  RUN_SCRIPT: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Determine docker image including current date
      run: echo "IMAGE=$IMAGE_REGION/$PROJECT_ID/gitbeaver:$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
    - name: Build the Docker image ${{ env.IMAGE }}
      run: docker build . --file Dockerfile --tag $IMAGE
    - name: Initialize gcloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_DOCKER_REPO_SA_KEY }}'
    - name: Configure docker
      run: gcloud auth configure-docker -q
    - name: Push docker image ${{ env.IMAGE }}
      run: docker push $IMAGE
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'terraform'
        tf_actions_comment: true
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: 'terraform'
        tf_actions_comment: true
        args: |
          -var="project_id=${{ env.PROJECT_ID }}" 
          -var="location=${{ env.LOCATION }}" 
          -var="network=${{ env.NETORK }}" 
          -var="service_account=${{ env.SERVICE_ACCOUNT }}" 
          -var="docker_image=${{ env.IMAGE }}"
          -var="run_git=${{ env.RUN_GIT }}"
          -var="run_repo=${{ env.RUN_REPO }}"
          -var="run_tag=${{ env.RUN_TAG }}"
          -var="run_script=${{ env.RUN_SCRIPT }}"