name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Determine docker image including current date
      run: echo "IMAGE=eu.gcr.io/breuni-infra-gitbeaver/gitbeaver:$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE
    - name: Initialize gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GOOGLE_DOCKER_REPO_SA_KEY }}
        project_id: breuni-infra-gitbeaver
        export_default_credentials: true
    - name: Configure docker
      run: gcloud auth configure-docker -q
    - name: Push docker image
      run: docker push $IMAGE
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'terraform'
        tf_actions_comment: true
