name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: breuninger-core-gitbeaver
  LOCATION: europe-west3
  TF_STATE_BUCKET: breuninger-terraform-remote-state
  TF_STATE_PATH: core/gitbeaver
  TF_VERSION: 1.1.8
  NETORK: projects/breuninger-core/locations/europe-west3/connectors/breuninger-core-network
  IMAGE_REGION: eu.gcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Determine docker image including current date
      run: echo "IMAGE=$IMAGE_REGION/$PROJECT_ID/gitbeaver:$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE
    - name: Initialize gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GOOGLE_DOCKER_REPO_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
    - name: Configure docker
      run: gcloud auth configure-docker -q
    - name: Push docker image
      run: docker push $IMAGE
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'terraform'
        tf_actions_comment: true
    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: 'terraform'
        tf_actions_comment: true
        args: '-var="project_id=${{ PROJECT_ID }} lccation=${{ LOCATION }} tf_state_bucket=${{ TF_STATE_BUCKET }} tf_state_path=${{ TF_STATE_PATH }} network=${{ NETORK }} docker_image=$IMAGE"'
